@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTcwNDYxNTU0OCwiZXhwIjoxNzA0NjU4NzQ4fQ.Wk4-8GrD0g_d3PCt2EWzKdgnXNkk0FbPzfXip-Ec65c

### 회원가입
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "name": "사용자이름",
  "email": "사용자이메일4@example.com",
  "password": "123123",
  "passwordConfirm": "123123"
}

### 로그인
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
	"email":"test02@test.com",
	"password":"456456"
}

### 회원정보조회
GET http://localhost:3001/api/users/info
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### 비밀번호 변경
PUT  http://localhost:3001/api/users/info
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "password": "123123",
  "newPassword": "456456",
  "passwordConfirm": "456456"
}