@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzA0NjkwNzY4LCJleHAiOjE3MDQ3MzM5Njh9.rEUooSCCLoMA_6hd3gJnlcmB2eN6ByIOecrTo31tduc

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzA0Njg2NDkxLCJleHAiOjE3MDQ3Mjk2OTF9.0q9fE_f0OW4NddLf6TUAifGCG8QGCyY1d_jlHYLI2IY
### 회원가입
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "name": "사용자이름",
  "email": "사용자이메일@example.com",
  "password": "123123",
  "passwordConfirm": "123123"
}


### 로그인
POST http://localhost:3001/api/auth/login
Content-Type: application/json
# Authorization: Bearer {{accessToken}}

{
  "email": "4사용자이메일4@example.com",
	"password":"456456"
}


### 회원정보조회
GET http://localhost:3001/api/users/info
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### 비밀번호 변경
PUT  http://localhost:3001/api/users/info
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "password": "123123",
  "newPassword": "456456",
  "passwordConfirm": "456456"
}

### 회원탈퇴
PUT  http://localhost:3001/api/users/delete
Content-Type: application/json
Authorization: Bearer {{accessToken}}