@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTcwNDg3MzQ2MywiZXhwIjoxNzA0OTE2NjYzfQ.ouc8KZNr1dBdO1SMSuRYOnydJG3p6ZC_-1tsqyIE97E
### 회원가입
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "name": "사용자",
  "email": "example@example.com",
  "password": "123123",
  "passwordConfirm": "123123"
}

### 로그인
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "example@example.com",
	"password":"123123"
}

### 회원정보조회
GET http://localhost:3001/api/user/info
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### 비밀번호 변경
PUT  http://localhost:3001/api/user/info
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "password": "123123",
  "newPassword": "456456",
  "passwordConfirm": "456456"
}

### 회원탈퇴
PUT  http://localhost:3001/api/user/delete
Content-Type: application/json
Authorization: Bearer {{accessToken}}