# @accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzA0NzAxOTg1LCJleHAiOjE3MDQ3NDUxODV9.JMhhvPNI3u7aARWdRqvVuBcLoPvmlxs3tXVp59eB_QA
# @accessToken =  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTcwNDcwMjAzMiwiZXhwIjoxNzA0NzQ1MjMyfQ.9Z85-g2YGokEg9BtKd93_SwE-FISTuq-ABfRak_-c1A
@accessToken =  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNzA0NzAzNDAwLCJleHAiOjE3MDQ3NDY2MDB9.5HJJ4HUFMYEstyw6RbKOV9RXyKCNkoJ5kyX_wGxm7MM

### 카드 생성하기
POST http://localhost:3001/api/card/list/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "cardName": "카드 이름0123",
  "cardDescription": "카드 상세내용",    
  "allowMembers": [8,9,10],
  "workers": [8,9],
  "cardColor": "red",
  "startDate": "2024-03-28",
  "endDate": "2024-05-30",
  "endTime": "17:00"
}

#

### 카드 수정하기
PATCH http://localhost:3001/api/card/39
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "cardName": "카드 수정한 이름3",
  "cardDescription": "카드 상세내용_ 수정했죠",
  "cardColor": "white",
  "allowMembers": [8,9],
  "workers": [9],
  "startDate": "2024-03-30",
  "endDate": "2024-05-20",
  "endTime": "19:00"
}

#

### 카드 삭제하기
DELETE http://localhost:3001/api/card/39
Content-Type: application/json
Authorization: Bearer {{accessToken}}


#

### 카드 상세정보 보기
GET http://localhost:3001/api/card/39
Content-Type: application/json
Authorization: Bearer {{accessToken}}

#

### 특정 리스트에 속한 모든 카드 보기
GET http://localhost:3001/api/card/list/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}






