@accessToken =  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTcwNDcwMjAzMiwiZXhwIjoxNzA0NzQ1MjMyfQ.9Z85-g2YGokEg9BtKd93_SwE-FISTuq-ABfRak_-c1A

### 리스트 생성하기
POST http://localhost:3001/api/list/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "listTitle": "erd 생성하기3"
}